### ISSUE TITLE
build失败：“Error: Found item String/sounds more than one time“

### ISSUE THREAD

**Issue by growvv** [AashifAhamed/MobileGameAndroid#1]
C:\Users\20928\Downloads\MobileGameAndroid-master\MobileGameAndroid-master\app\src\main\res\values\strings.xml: Error: Found item String/sounds more than one time
请问如何解决？

**Comment by AashifAhamed** [comment]
Thank you for reporting. Now it fixed.
Cannot have multiple strings with the same name ("_0") in your case. Give a unique name to each of them as follows

`<resources>

    <string name="app_name">CourtCounter</string>

    <string name="button1">Button1</string>

    <string name="very_hard">Very Hard</string>

    <string name="_0">0</string>

</resources>  `

`<string name="_0">0</string>` have duplicates simply remove it.
